### ISSUE TITLE
Plugins List ??

### ISSUE THREAD

**Issue by pratikraman-dev** [phodal/cordova-wordpress#2]
Which Plugins Should Be Added or anything else.....app is not working on mobille....... on android Its Just Loading But post are not displaying .......any plugins i have to add before build or any steps i have missed ??
1. cordova platform add android 
2. cordova build

trying to run not working

**Comment by phodal** [comment]
Hi @pratt1305, 

In this case ,I use this https://wordpress.org/plugins/json-rest-api/ which is a Wordpress plugin. Finally , I use Django replace Wordpress, so this project isn't on going.

**Comment by pratikraman-dev** [comment]
Means App Will Not Work.............

**Comment by phodal** [comment]
@pratt1305 , you can try.

**Comment by pratikraman-dev** [comment]
thanks i'll try if works i'll contribute....it
